spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-service
      auto-offset-reset: earliest
      properties:
          spring.json.trusted.packages: "*"
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      username: dev
      database: dev
      authentication-database: admin
      password: dev
logging:
  level:
    org.springframework.kafka: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG