{{if .Values.secretStores.vault }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "user-svc.fullname" . }}-external-secret
  labels:
    {{- include "user-svc.labels" . | nindent 4 }}
spec:
  refreshInterval: "10s"
  secretStoreRef:
    name: {{ include "user-svc.fullname" . }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Values.secretRef.name }}
  data:
    - secretKey: mongodb-passwords
      remoteRef:
        key: se347/backend/dev/user-svc
        property: mongodb-passwords
    - secretKey: mongodb-replica-set-key
      remoteRef:
        key: se347/backend/dev/user-svc
        property: mongodb-replica-set-key
    - secretKey: mongodb-root-password
      remoteRef:
        key: se347/backend/dev/user-svc
        property: mongodb-root-password
{{- end }}