{{- if .Values.secretStores.vault }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "user-svc.fullname" . }}-secret-store
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "user-svc.labels" . | nindent 4 }}
spec:
  provider:
      vault:
      {{- .Values.secretStores.vault |toYaml | nindent 8 }}
{{ end }}