apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-svc.fullname" . -}}-mongo-cm
  labels:
    {{- include "user-svc.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.db }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}