apiVersion: v1
kind: Service
metadata:
  name: user-svc-mongodb
  labels:
    {{- include "user-svc.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: user-svc-mongodb
    app.kubernetes.part-of: user-svc
    app.kubernetes.io/instance: user-svc
  ports:
    - name: mongodb-port
      port: 27017
      targetPort: 27017
      protocol: TCP