apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-svc.fullname" . -}}-configmap
  labels:
    {{- include "user-svc.labels" . | nindent 4 }}
data:
  APP_VERSION: {{ .Values.image.tag | quote }}
  {{- range $key, $value := .Values.configMap.app }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}