spring:
  config:
    import:
      - "optional:dev.yaml"
  application:
    name: se347-backend
server:
  port: 5000
  forward-headers-strategy: native
springdoc:
  open-api:
    info:
      version: ${APP_VERSION}
      title: User Service management API
      description: Contains endpoints for managing users
      contact:
        name: NgoDat0103
        url: https://github.com/NGODAT0103
        email: 21521935@gm.uit.edu.vn
  api-docs:
    path: /api/v1/api-docs
  swagger-ui:
    path: /api/v1/ui-docs
    use-root-path: true
  show-actuator: true