spring:
  config:
    activate:
      on-profile: dev
  kafka:
    producer:
      bootstrap-servers: kafka-svc
  data:
    mongodb:
      host: 127.0.0.1
      username: dev
      password: dev
      database: se347-backend
      auto-index-creation: true
    redis:
      repositories:
        enabled: false
      client-name: se347-backend
      client-type: lettuce
      host: 127.0.0.1
jwk:
  rsa: #Dev credential
    key-value: |-
      {
      "p": "1j0tHGqgBAIMYgDVBm4NlkjNUNC4IXSDmXzt7HzDHg-kV9xY5CRam94DjfMKeMzhSnByV9iShzl5K13BLMZ95FYXIjP_tpPAppg67bth8nT7uEz0q628DA6-LPCjpEABjSl-f63tz8Bt9EcfRjOEaCtcpcG_XXDUQ4FthxU3UZLKjHdVxY8_NORWzruBeF8ycZ5FMTiEhtJeSr35ITLh7A7xc469kUXwhYvPkqgNHvkQjYZN7O4ojK2q4sJoPOw-ChLg3VyeFM9an1bsfkh3qy2-uO_SmZNG-ctlxkARAmSraa0raNEpYVqS1z2ucfY2V33i35tM4Ijr4OYVKaTciQ",
      "kty": "RSA",
      "q": "4-q4QeFFnImDryHoO-fDWgLaN2bGUgt7TGHu1WbSa91N06AT4w1PskaNR8lLCIFtu6HThAb2WtdhfZABebtDrEIw5l7zaetxO2El3pVY_gcvCFPunQxZQ4S39F3CIfOTaCTA1-DYxXNSk71Gq2ONYeioQlf2WEPveCGs93sY2iBpXDLBUl2rhu5p3DILHLmPg1yNfqRFhetNLlMFKPijLpJCsnE1b0An1hEWu_z2gOts-lJwuifesnuGqgswDOcloEtmf6_xor_zLq82fzH00ReYU3PyQCccPZ66upCg3z89qwqYCcQ2-JUspJwmUuvOvjdvSh3s3DYh67qlsrKT0w",
      "d": "DJbcKlwf5dHaOLzHNEPgXNebotc-BpMsf5yjtZ7fU6L-GLXxvlsWREx2jCy18mjMfi3VycMQe-1DTMHf_kkPlcf90APYuGI9gCVwARRuw1aif6BCaLphN72yJyvf_kDGdLnL33mIIn2WRlseuVehg2TmVNxozrHBXyezCkwbcthBRRB4xd58cK2mBX7ivDM96AZnx5xOkL45xte1A3btvSeKS2e--f3BC1P_Gp0fdBynTm3KUvfhNwnTeqPhjaxASbD3_9TNBfgCmo9VByFpLIRKdnBL8jpzFtHtRlVRbWFukFucid0ofSechBFJ3u1Yh9jdI59zRLhyrFVaDEeAAfdRmzGXwg719qq_ryxI8lAbLF3z3N7oA8_Zu29QjMTanXK6VGQ22FMH7l95xaGmlVd_xYc6_kdPx6mgocljFrPewB6nkpyvFUABxn2j_BNnHYQgJK9AyjKDd0K9lLp12Ki10rWrSAu6XBIY8Q35gAQu7qXGiKbS1FIlEk8FWuQnheQXdVyAeYgBvQQZXHp8GJYvZ7MfKKgxgfslgmF69foyth-llYPJFEyNMMTubr67uYjWExQ-Qkg0VvGSPDvs8Ra2mzfcwvk4j5Z544ZA8SNUdITc2E1cakMU1OH0DdmCKKayW7Lgzzse8LgHZJCGaHXSO_RUgNse85ayuJYHRjE",
      "e": "AQAB",
      "qi": "Irdz8v2cNgQn4GJ-f7DJKqnbiJlgszzDDniwM6556vpGV21sx-jFfxzXxn12Ad100eYX8TjEb_hVpjRCggJywiTQ26F-Tpmn3YD3-g4lAf3L5YcrbZNEVXG0s66ZmncPtaTlgKHQtf-cRsWjvaMKDewx6Sxe6EOCnySaBC20WdZdPGXE28iTz75T_8DLaIcqh3Yq31pala3yWLrlvE7sRALaLQe1tGzhb3bvv1_rHEPvf8OgbEQMYl9Snh79IKulK0sN9q4iSla3XjtRh79ZYSEvss77c5Dm1InCi3qgw8OAc7tfh4iV1-TczLQcyEQhxT9NHKGID4olI5ooTD66HA",
      "dp": "QGA_pvNPRAUNjYFsgbMeOBOGRouBWOQ3Cy8kG1TeGLFgk9oth9h4ta9_5-6pLeV6qTCi20zDswiNJX_VpUu71pob93Yil81MLYM-6eLNqtqGLTpKpy_ces8PTFe_BIMLNEzMqzcrZ6sOH0Ij3qdqWRb2jwRqKXzW-7XvoJC6f7OZU54kUuoZdx5KC3MCk5YfhU6mwgSWpiCentz4-IXep11SJoQ06GtYu_hoFkyTLMRwueYqklB6NNOWru71_aCLf-FuWnYTNnOcapbnF4dVFkX3soC2CtnbkQISggEMW2i-rVGQ4r0_LvbVewIY4ju21pGIU-LJtgrOvlTE9S-J6Q",
      "dq": "efEDVHwqum34vqLtld-SbX5JMosSYKMz_NII7rRssLlfAnMLMNfWZBPLUzUnqA1XoKQcfu8ar8-8oWmC4JaIxolDkH4MzgbiNlrr4AMX8hH14AbIC86nk7BWm6_uRiwEGhxP8TCjykDBVbpXLSu-YTwRii116BOw9B1QZbi-uzXMKUAenuru8upsSRudRmkhl67VJYTOjbAvQzG3-QvOgwROGxrm8_bnWWkbOMlHOgK789JX7cGXLPdaPXBu7Phe8TxmQrroFaONgNTN24_m5Fgzb7MBUcGbInziex8Wc1tqqzCn19Hbd3SYxhmlh4gSvUL7kDQink94Jp9eOBXDcQ",
      "n": "vrytHokAQM8PKmnaTcoGKHBk_Yvv2jHa4WQ7tb3kGK2LUNMlwYOO4ySQrXoFHc__d09SOAlJTkhGMMu1SGbtzVrb9XIMDBcnJFV3mORaVkpmwTa0pC1UdZa6tc7AOsDvQvMJAvuoGMzkhEE-G-A1_q7Ygv45gs4TCA2LX168GJodoSLjRxKe_casuGJ97IIWZ_sYmcxnbsaQvhmtItrEXpvF3FXqNKLPjgnPbaM1CmcPWkcF52R7RT60N0b4YO2Nf_dDI7vfkxaK6c2XoYhaTo_APtEhlkkbrGqwu1NBHxTtYoIiX4poQdDfNs9ym64jsqxG45GKebM5q18quh6D6SWLkYUOveFAcHJpYLeKqUpCuezg66W3_Aybh9CVuc0yx0iSDZE7_qbFx9vC1KHtfLJ0VqWYVHJLgGmK_bHw9rUd881z_mgHhpOytIuFFtT6FLs-FS2NF6gXgITSFa8nmEQQw0l40nqYK9_X7B-MQilWfWcieWe2pa_X_88XC3ikEx6APHRWdZ88GOXbDzoCvw3Q2z2D4qaVW5O1GIGuz9cQuI8WzYrOqCW6NqnQ41dI5eGfLPxtHZXrI_jwQ4ezX3aB0rl4SC9lDoCaaAs3Ws5kEOrQ2bbfgveaQlyw4geEWzvWYj7ysUm2Dl7_IYXVRnRhfJwhBXo2-mgOoJbGb-s"
      }
minio:
  bucket: dev-se347
