name: dev-user-svc-pipeline
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/dev-se34-backend-pipeline.yaml'
      - 'se347-backend/src/main/**'
      - 'se347-backend/compose.yaml'
    branches:
      - dev
jobs:
  se347-backend-pipline:
    uses: ./.github/workflows/dev-java-pipeline-template.yaml
    secrets: inherit
    with:
      SERVICE_NAME: se347-backend
      SERVICE_PORT: 5000
      BRANCH_NAME: dev

