name: dev-user-svc-pipeline
on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/dev-pipeline.yaml'
      - 'user-svc/src/main/**'
      - 'user-svc/compose.yaml'
    branches:
      - dev
jobs:
  user-svc-ci:
    uses: ./.github/workflows/dev-java-ci-template.yaml
    secrets: inherit
    with:
      SERVICE_NAME: user-svc
      SERVICE_PORT: 5000
      BRANCH_NAME: dev

